# Site settings
title: "SchoolPlatform - EdTech Blockchain MVP"
email: "info@matteoricci.net"
description: >-
  MVP blockchain educational platform ready for scale. 18-month development complete. 
  Production-ready technology stack serving the $400B+ EdTech market. Investment opportunity.

baseurl: "/gh-pages" # o "/docs-site" - il nome del repository
url: "https://pyzenmatt.github.io" # sostituisci con il tuo username GitHub reale

# Author
author:
  name: "Matteo Ricci"
  email: "matteoricci12@.com"

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima  # Rimosso per compatibilità GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Main Navigation (English is default)
navigation:
  - title: "Home"
    url: "/"
  - title: "Features"
    url: "/eng/features/"
  - title: "Technology"
    url: "/eng/technology/"
  - title: "Tokenomics"
    url: "/eng/tokenomics/"
  - title: "Roadmap"
    url: "/eng/roadmap/"
  - title: "FAQ"
    url: "/eng/faq/"
  - title: "Invest"
    url: "/eng/invest/"
  - title: "Contact"
    url: "/eng/contact/"

# Italian Navigation
navigation_it:
  - title: "Home"
    url: "/ita/"
  - title: "Features"
    url: "/ita/features/"
  - title: "Technology"
    url: "/ita/technology/"
  - title: "Tokenomics"
    url: "/ita/tokenomics/"
  - title: "Roadmap"
    url: "/ita/roadmap/"
  - title: "FAQ"
    url: "/ita/faq/"
  - title: "Contatti"
    url: "/ita/invest/#founder"

# English Navigation (for consistency)
navigation_en:
  - title: "Home"
    url: "/"
  - title: "Features"
    url: "/eng/features/"
  - title: "Technology"
    url: "/eng/technology/"
  - title: "Roadmap"
    url: "/eng/roadmap/"
  - title: "FAQ"
    url: "/eng/faq/"
  - title: "Invest"
    url: "/eng/invest/"
  - title: "Contact"
    url: "/eng/invest/#founder"

# Social links
github_username: tuousername  # sostituisci con il tuo username GitHub
# linkedin_username: tuolinkedin # sostituisci con il tuo username LinkedIn

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  features:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
